const keywords = [
    {
        "word": "Self Controlled",
        "id": "1",
        "primary_group": "R",
        "secondary_group": "o",
        "type": "1",
        "level": "L5",
        "page": "393",
        "page2": "393",
        "center": "IN",
        "tooltip": "Self Controlled"
    },
    {
        "word": "Conscientious",
        "id": "2",
        "primary_group": "R",
        "secondary_group": "o",
        "type": "1",
        "level": "L3",
        "page": "126",
        "page2": "126",
        "center": "IN",
        "tooltip": "Conscientious"
    },
    {
        "word": "Striving",
        "id": "3",
        "primary_group": "R",
        "secondary_group": "o",
        "type": "1",
        "level": "L4",
        "page": "109",
        "page2": "109",
        "center": "IN",
        "tooltip": "Striving"
    },
    {
        "word": "Orderly",
        "id": "4",
        "primary_group": "R",
        "secondary_group": "o",
        "type": "1",
        "level": "L5",
        "page": "112",
        "page2": "112",
        "center": "IN",
        "tooltip": "Orderly"
    },
    {
        "word": "Perfectionistic",
        "id": "5",
        "primary_group": "R",
        "secondary_group": "o",
        "type": "1",
        "level": "L6",
        "page": "394",
        "page2": "395",
        "center": "IN",
        "tooltip": "Perfectionistic"
    },
    {
        "word": "Obligated",
        "id": "6",
        "primary_group": "R",
        "secondary_group": "o",
        "type": "1",
        "level": "L4",
        "page": "391",
        "page2": "391",
        "center": "IN",
        "tooltip": "Obligated"
    },
    {
        "word": "Punctual",
        "id": "7",
        "primary_group": "R",
        "secondary_group": "o",
        "type": "1",
        "level": "L5",
        "page": "392",
        "page2": "392",
        "center": "IN",
        "tooltip": "Punctual"
    },
    {
        "word": "Serious",
        "id": "8",
        "primary_group": "R",
        "secondary_group": "o",
        "type": "1",
        "level": "L4",
        "page": "391",
        "page2": "391",
        "center": "IN",
        "tooltip": "Serious"
    },
    {
        "word": "Correcting",
        "id": "9",
        "primary_group": "R",
        "secondary_group": "o",
        "type": "1",
        "level": "L6",
        "page": "128",
        "page2": "128",
        "center": "IN",
        "tooltip": "Correcting"
    },
    {
        "word": "Critical",
        "id": "10",
        "primary_group": "R",
        "secondary_group": "o",
        "type": "1",
        "level": "L6",
        "page": "396",
        "page2": "397",
        "center": "IN",
        "tooltip": "Critical"
    },
    {
        "word": "Needing closeness",
        "id": "11",
        "primary_group": "G",
        "secondary_group": "f",
        "type": "2",
        "level": "L4",
        "page": "72",
        "page2": "72",
        "center": "FE",
        "tooltip": "Needing closeness"
    },
    {
        "word": "Nurturing",
        "id": "12",
        "primary_group": "G",
        "secondary_group": "f",
        "type": "2",
        "level": "L3",
        "page": "71",
        "page2": "71",
        "center": "FE",
        "tooltip": "Nurturing"
    },
    {
        "word": "Generous to a Fault",
        "id": "13",
        "primary_group": "G",
        "secondary_group": "f",
        "type": "2",
        "level": "L5",
        "page": "77",
        "page2": "77",
        "center": "FE",
        "tooltip": "Generous to a Fault"
    },
    {
        "word": "Serving",
        "id": "14",
        "primary_group": "G",
        "secondary_group": "f",
        "type": "2",
        "level": "L3",
        "page": "70",
        "page2": "70",
        "center": "FE",
        "tooltip": "Serving"
    },
    {
        "word": "Deeply Caring",
        "id": "15",
        "primary_group": "G",
        "secondary_group": "f",
        "type": "2",
        "level": "L2",
        "page": "69",
        "page2": "69",
        "center": "FE",
        "tooltip": "Deeply Caring"
    },
    {
        "word": "Generous",
        "id": "16",
        "primary_group": "G",
        "secondary_group": "f",
        "type": "2",
        "level": "L3",
        "page": "70",
        "page2": "71",
        "center": "FE",
        "tooltip": "Generous"
    },
    {
        "word": "People person",
        "id": "17",
        "primary_group": "G",
        "secondary_group": "f",
        "type": "2",
        "level": "L4",
        "page": "72",
        "page2": "72",
        "center": "FE",
        "tooltip": "People person"
    },
    {
        "word": "Martyring Self",
        "id": "18",
        "primary_group": "G",
        "secondary_group": "f",
        "type": "2",
        "level": "L6",
        "page": "75",
        "page2": "75",
        "center": "FE",
        "tooltip": "Martyring Self"
    },
    {
        "word": "Possessive",
        "id": "19",
        "primary_group": "G",
        "secondary_group": "f",
        "type": "2",
        "level": "L5",
        "page": "76",
        "page2": "76",
        "center": "FE",
        "tooltip": "Possessive"
    },
    {
        "word": "Approving",
        "id": "20",
        "primary_group": "G",
        "secondary_group": "f",
        "type": "2",
        "level": "L4",
        "page": "74",
        "page2": "74",
        "center": "FE",
        "tooltip": "Approving"
    },
    {
        "word": "Charming",
        "id": "21",
        "primary_group": "G",
        "secondary_group": "g",
        "type": "3",
        "level": "L2",
        "page": "107",
        "page2": "107",
        "center": "FE",
        "tooltip": "Charming"
    },
    {
        "word": "Performing",
        "id": "22",
        "primary_group": "G",
        "secondary_group": "g",
        "type": "3",
        "level": "L4",
        "page": "110",
        "page2": "111",
        "center": "FE",
        "tooltip": "Performing"
    },
    {
        "word": "Role model",
        "id": "23",
        "primary_group": "G",
        "secondary_group": "g",
        "type": "3",
        "level": "L3",
        "page": "108",
        "page2": "108",
        "center": "FE",
        "tooltip": "Role model"
    },
    {
        "word": "Appropriate",
        "id": "24",
        "primary_group": "G",
        "secondary_group": "g",
        "type": "3",
        "level": "L5",
        "page": "113",
        "page2": "113",
        "center": "FE",
        "tooltip": "Appropriate"
    },
    {
        "word": "Ambitious",
        "id": "25",
        "primary_group": "G",
        "secondary_group": "g",
        "type": "3",
        "level": "L3",
        "page": "80",
        "page2": "80",
        "center": "FE",
        "tooltip": "Ambitious"
    },
    {
        "word": "Efficient",
        "id": "26",
        "primary_group": "G",
        "secondary_group": "g",
        "type": "3",
        "level": "L4",
        "page": "107",
        "page2": "107",
        "center": "FE",
        "tooltip": "Efficient"
    },
    {
        "word": "The Best",
        "id": "27",
        "primary_group": "G",
        "secondary_group": "g",
        "type": "3",
        "level": "L4",
        "page": "109",
        "page2": "110",
        "center": "FE",
        "tooltip": "The Best"
    },
    {
        "word": "Arrogant",
        "id": "28",
        "primary_group": "G",
        "secondary_group": "g",
        "type": "3",
        "level": "L6",
        "page": "81",
        "page2": "81",
        "center": "FE",
        "tooltip": "Arrogant"
    },
    {
        "word": "Seek Recognition",
        "id": "29",
        "primary_group": "G",
        "secondary_group": "g",
        "type": "3",
        "level": "L4",
        "page": "109",
        "page2": "109",
        "center": "FE",
        "tooltip": "Seek Recognition"
    },
    {
        "word": "Image Conscious",
        "id": "30",
        "primary_group": "G",
        "secondary_group": "g",
        "type": "3",
        "level": "L5",
        "page": "111",
        "page2": "111",
        "center": "FE",
        "tooltip": "Image Conscious"
    },
    {
        "word": "Self Indulgent",
        "id": "31",
        "primary_group": "G",
        "secondary_group": "t",
        "type": "4",
        "level": "L6",
        "page": "156",
        "page2": "156",
        "center": "FE",
        "tooltip": "Self Indulgent"
    },
    {
        "word": "Self-Absorbed",
        "id": "32",
        "primary_group": "G",
        "secondary_group": "t",
        "type": "4",
        "level": "L5",
        "page": "155",
        "page2": "155",
        "center": "FE",
        "tooltip": "Self-Absorbed"
    },
    {
        "word": "Introspective",
        "id": "33",
        "primary_group": "G",
        "secondary_group": "t",
        "type": "4",
        "level": "L2",
        "page": "180",
        "page2": "180",
        "center": "FE",
        "tooltip": "Introspective"
    },
    {
        "word": "Mysterious",
        "id": "34",
        "primary_group": "G",
        "secondary_group": "t",
        "type": "4",
        "level": "L4",
        "page": "154",
        "page2": "154",
        "center": "FE",
        "tooltip": "Mysterious"
    },
    {
        "word": "Special",
        "id": "35",
        "primary_group": "G",
        "secondary_group": "t",
        "type": "4",
        "level": "L4",
        "page": "117",
        "page2": "117",
        "center": "FE",
        "tooltip": "Special"
    },
    {
        "word": "Self-Revealing",
        "id": "36",
        "primary_group": "G",
        "secondary_group": "t",
        "type": "4",
        "level": "L3",
        "page": "180",
        "page2": "180",
        "center": "FE",
        "tooltip": "Self-Revealing"
    },
    {
        "word": "Brooding",
        "id": "37",
        "primary_group": "G",
        "secondary_group": "t",
        "type": "4",
        "level": "L5",
        "page": "181",
        "page2": "181",
        "center": "FE",
        "tooltip": "Brooding"
    },
    {
        "word": "Self-Pitying",
        "id": "38",
        "primary_group": "G",
        "secondary_group": "t",
        "type": "4",
        "level": "L6",
        "page": "87",
        "page2": "87",
        "center": "FE",
        "tooltip": "Self-Pitying"
    },
    {
        "word": "Aesthetic",
        "id": "39",
        "primary_group": "G",
        "secondary_group": "t",
        "type": "4",
        "level": "L4",
        "page": "150",
        "page2": "150",
        "center": "FE",
        "tooltip": "Aesthetic"
    },
    {
        "word": "Temperamental",
        "id": "40",
        "primary_group": "G",
        "secondary_group": "t",
        "type": "4",
        "level": "L5",
        "page": "153",
        "page2": "153",
        "center": "FE",
        "tooltip": "Temperamental"
    },
    {
        "word": "Unsentimental",
        "id": "41",
        "primary_group": "B",
        "secondary_group": "l",
        "type": "5",
        "level": "L3",
        "page": "184",
        "page2": "184",
        "center": "TH",
        "tooltip": "Unsentimental"
    },
    {
        "word": "Inventive",
        "id": "42",
        "primary_group": "B",
        "secondary_group": "l",
        "type": "5",
        "level": "L3",
        "page": "92",
        "page2": "92",
        "center": "TH",
        "tooltip": "Inventive"
    },
    {
        "word": "Intense",
        "id": "43",
        "primary_group": "B",
        "secondary_group": "l",
        "type": "5",
        "level": "L5",
        "page": "93",
        "page2": "93",
        "center": "TH",
        "tooltip": "Intense"
    },
    {
        "word": "Speculative",
        "id": "44",
        "primary_group": "B",
        "secondary_group": "l",
        "type": "5",
        "level": "L5",
        "page": "193",
        "page2": "193",
        "center": "TH",
        "tooltip": "Speculative"
    },
    {
        "word": "Detached",
        "id": "45",
        "primary_group": "B",
        "secondary_group": "l",
        "type": "5",
        "level": "L5",
        "page": "194",
        "page2": "194",
        "center": "TH",
        "tooltip": "Detached"
    },
    {
        "word": "Specialized",
        "id": "46",
        "primary_group": "B",
        "secondary_group": "l",
        "type": "5",
        "level": "L4",
        "page": "188",
        "page2": "188",
        "center": "TH",
        "tooltip": "Specialized"
    },
    {
        "word": "Subversive",
        "id": "47",
        "primary_group": "B",
        "secondary_group": "l",
        "type": "5",
        "level": "L6",
        "page": "195",
        "page2": "196",
        "center": "TH",
        "tooltip": "Subversive"
    },
    {
        "word": "Analytical",
        "id": "48",
        "primary_group": "B",
        "secondary_group": "l",
        "type": "5",
        "level": "L4",
        "page": "189",
        "page2": "189",
        "center": "TH",
        "tooltip": "Analytical"
    },
    {
        "word": "Secretive",
        "id": "49",
        "primary_group": "B",
        "secondary_group": "l",
        "type": "5",
        "level": "L5",
        "page": "191",
        "page2": "191",
        "center": "TH",
        "tooltip": "Secretive"
    },
    {
        "word": "Curious",
        "id": "50",
        "primary_group": "B",
        "secondary_group": "l",
        "type": "5",
        "level": "L2",
        "page": "182",
        "page2": "182",
        "center": "TH",
        "tooltip": "Curious"
    },
    {
        "word": "Doubting",
        "id": "51",
        "primary_group": "B",
        "secondary_group": "b",
        "type": "6",
        "level": "L5",
        "page": "138",
        "page2": "138",
        "center": "TH",
        "tooltip": "Doubting"
    },
    {
        "word": "Worrying",
        "id": "52",
        "primary_group": "B",
        "secondary_group": "b",
        "type": "6",
        "level": "L4",
        "page": "232",
        "page2": "232",
        "center": "TH",
        "tooltip": "Worrying"
    },
    {
        "word": "Suspicious",
        "id": "53",
        "primary_group": "B",
        "secondary_group": "b",
        "type": "6",
        "level": "L6",
        "page": "242",
        "page2": "242",
        "center": "TH",
        "tooltip": "Suspicious"
    },
    {
        "word": "Vigilant",
        "id": "54",
        "primary_group": "B",
        "secondary_group": "b",
        "type": "6",
        "level": "L2",
        "page": "229",
        "page2": "229",
        "center": "TH",
        "tooltip": "Vigilant"
    },
    {
        "word": "Cautious",
        "id": "55",
        "primary_group": "B",
        "secondary_group": "b",
        "type": "6",
        "level": "L5",
        "page": "237",
        "page2": "237",
        "center": "TH",
        "tooltip": "Cautious"
    },
    {
        "word": "Prepared",
        "id": "56",
        "primary_group": "B",
        "secondary_group": "b",
        "type": "6",
        "level": "L4",
        "page": "232",
        "page2": "232",
        "center": "TH",
        "tooltip": "Prepared"
    },
    {
        "word": "Cooperative",
        "id": "57",
        "primary_group": "B",
        "secondary_group": "b",
        "type": "6",
        "level": "L3",
        "page": "231",
        "page2": "231",
        "center": "TH",
        "tooltip": "Cooperative"
    },
    {
        "word": "Ambivalent",
        "id": "58",
        "primary_group": "B",
        "secondary_group": "b",
        "type": "6",
        "level": "L5",
        "page": "238",
        "page2": "238",
        "center": "TH",
        "tooltip": "Ambivalent"
    },
    {
        "word": "Dutiful",
        "id": "59",
        "primary_group": "B",
        "secondary_group": "b",
        "type": "6",
        "level": "L4",
        "page": "232",
        "page2": "234",
        "center": "TH",
        "tooltip": "Dutiful"
    },
    {
        "word": "Committed",
        "id": "60",
        "primary_group": "B",
        "secondary_group": "b",
        "type": "6",
        "level": "L3",
        "page": "231",
        "page2": "231",
        "center": "TH",
        "tooltip": "Committed"
    },
    {
        "word": "Keep options open",
        "id": "61",
        "primary_group": "B",
        "secondary_group": "w",
        "type": "7",
        "level": "L4",
        "page": "273",
        "page2": "273",
        "center": "TH",
        "tooltip": "Keep options open"
    },
    {
        "word": "Accomplished",
        "id": "62",
        "primary_group": "B",
        "secondary_group": "w",
        "type": "7",
        "level": "L3",
        "page": "271",
        "page2": "271",
        "center": "TH",
        "tooltip": "Accomplished"
    },
    {
        "word": "Versatile",
        "id": "63",
        "primary_group": "B",
        "secondary_group": "w",
        "type": "7",
        "level": "L3",
        "page": "271",
        "page2": "271",
        "center": "TH",
        "tooltip": "Versatile"
    },
    {
        "word": "Spontaneous",
        "id": "64",
        "primary_group": "B",
        "secondary_group": "w",
        "type": "7",
        "level": "L2",
        "page": "270",
        "page2": "270",
        "center": "TH",
        "tooltip": "Spontaneous"
    },
    {
        "word": "Uninhibited",
        "id": "65",
        "primary_group": "B",
        "secondary_group": "w",
        "type": "7",
        "level": "L5",
        "page": "276",
        "page2": "277",
        "center": "TH",
        "tooltip": "Uninhibited"
    },
    {
        "word": "Seeking Variety",
        "id": "66",
        "primary_group": "B",
        "secondary_group": "w",
        "type": "7",
        "level": "L4",
        "page": "272",
        "page2": "272",
        "center": "TH",
        "tooltip": "Seeking Variety"
    },
    {
        "word": "Irreverent",
        "id": "67",
        "primary_group": "B",
        "secondary_group": "w",
        "type": "7",
        "level": "L5",
        "page": "276",
        "page2": "277",
        "center": "TH",
        "tooltip": "Irreverent"
    },
    {
        "word": "Hyperactive",
        "id": "68",
        "primary_group": "B",
        "secondary_group": "w",
        "type": "7",
        "level": "L5",
        "page": "276",
        "page2": "276",
        "center": "TH",
        "tooltip": "Hyperactive"
    },
    {
        "word": "Excessive",
        "id": "69",
        "primary_group": "B",
        "secondary_group": "w",
        "type": "7",
        "level": "L6",
        "page": "280",
        "page2": "280",
        "center": "TH",
        "tooltip": "Excessive"
    },
    {
        "word": "Scattered",
        "id": "70",
        "primary_group": "B",
        "secondary_group": "w",
        "type": "7",
        "level": "L5",
        "page": "278",
        "page2": "278",
        "center": "TH",
        "tooltip": "Scattered"
    },
    {
        "word": "Empowering",
        "id": "71",
        "primary_group": "R",
        "secondary_group": "p",
        "type": "8",
        "level": "L3",
        "page": "310",
        "page2": "310",
        "center": "IN",
        "tooltip": "Empowering"
    },
    {
        "word": "Protective",
        "id": "72",
        "primary_group": "R",
        "secondary_group": "p",
        "type": "8",
        "level": "L3",
        "page": "310",
        "page2": "310",
        "center": "IN",
        "tooltip": "Protective"
    },
    {
        "word": "No Nonsense",
        "id": "73",
        "primary_group": "R",
        "secondary_group": "p",
        "type": "8",
        "level": "L4",
        "page": "312",
        "page2": "312",
        "center": "IN",
        "tooltip": "No Nonsense"
    },
    {
        "word": "Decisive",
        "id": "74",
        "primary_group": "R",
        "secondary_group": "p",
        "type": "8",
        "level": "L3",
        "page": "310",
        "page2": "310",
        "center": "IN",
        "tooltip": "Decisive"
    },
    {
        "word": "Territorial",
        "id": "75",
        "primary_group": "R",
        "secondary_group": "p",
        "type": "8",
        "level": "L5",
        "page": "318",
        "page2": "318",
        "center": "IN",
        "tooltip": "Territorial"
    },
    {
        "word": "Risk Taking",
        "id": "76",
        "primary_group": "R",
        "secondary_group": "p",
        "type": "8",
        "level": "L4",
        "page": "315",
        "page2": "315",
        "center": "IN",
        "tooltip": "Risk Taking"
    },
    {
        "word": "Dominant",
        "id": "77",
        "primary_group": "R",
        "secondary_group": "p",
        "type": "8",
        "level": "L5",
        "page": "319",
        "page2": "319",
        "center": "IN",
        "tooltip": "Dominant"
    },
    {
        "word": "Pushing Limits",
        "id": "78",
        "primary_group": "R",
        "secondary_group": "p",
        "type": "8",
        "level": "L6",
        "page": "320",
        "page2": "320",
        "center": "IN",
        "tooltip": "Pushing Limits"
    },
    {
        "word": "Assertive",
        "id": "79",
        "primary_group": "R",
        "secondary_group": "p",
        "type": "8",
        "level": "L2",
        "page": "308",
        "page2": "308",
        "center": "IN",
        "tooltip": "Assertive"
    },
    {
        "word": "Tough",
        "id": "80",
        "primary_group": "R",
        "secondary_group": "p",
        "type": "8",
        "level": "L5",
        "page": "298",
        "page2": "298",
        "center": "IN",
        "tooltip": "Tough"
    },
    {
        "word": "Stubborn",
        "id": "81",
        "primary_group": "R",
        "secondary_group": "r",
        "type": "9",
        "level": "L6",
        "page": "360",
        "page2": "360",
        "center": "IN",
        "tooltip": "Stubborn"
    },
    {
        "word": "Easygoing",
        "id": "82",
        "primary_group": "R",
        "secondary_group": "r",
        "type": "9",
        "level": "L4",
        "page": "356",
        "page2": "356",
        "center": "IN",
        "tooltip": "Easygoing"
    },
    {
        "word": "Mediating",
        "id": "83",
        "primary_group": "R",
        "secondary_group": "r",
        "type": "9",
        "level": "L3",
        "page": "351",
        "page2": "351",
        "center": "IN",
        "tooltip": "Mediating"
    },
    {
        "word": "Agreeable",
        "id": "84",
        "primary_group": "R",
        "secondary_group": "r",
        "type": "9",
        "level": "L4",
        "page": "353",
        "page2": "353",
        "center": "IN",
        "tooltip": "Agreeable"
    },
    {
        "word": "Patient",
        "id": "85",
        "primary_group": "R",
        "secondary_group": "r",
        "type": "9",
        "level": "L3",
        "page": "351",
        "page2": "351",
        "center": "IN",
        "tooltip": "Patient"
    },
    {
        "word": "Comfort Seeking",
        "id": "86",
        "primary_group": "R",
        "secondary_group": "r",
        "type": "9",
        "level": "L5",
        "page": "357",
        "page2": "357",
        "center": "IN",
        "tooltip": "Comfort Seeking"
    },
    {
        "word": "Self Effacing",
        "id": "87",
        "primary_group": "R",
        "secondary_group": "r",
        "type": "9",
        "level": "L4",
        "page": "354",
        "page2": "354",
        "center": "IN",
        "tooltip": "Self Effacing"
    },
    {
        "word": "Unselfconscious",
        "id": "88",
        "primary_group": "R",
        "secondary_group": "r",
        "type": "9",
        "level": "L2",
        "page": "164",
        "page2": "165",
        "center": "IN",
        "tooltip": "Unselfconscious"
    },
    {
        "word": "Avoid Conflicts",
        "id": "89",
        "primary_group": "R",
        "secondary_group": "r",
        "type": "9",
        "level": "L5",
        "page": "358",
        "page2": "359",
        "center": "IN",
        "tooltip": "Avoid Conflicts"
    },
    {
        "word": "Neutral",
        "id": "90",
        "primary_group": "R",
        "secondary_group": "r",
        "type": "9",
        "level": "L5",
        "page": "353",
        "page2": "356",
        "center": "IN",
        "tooltip": "Neutral"
    }
]

module.exports = keywords;
